#!/usr/bin/env bash
# included in every script
source `dirname $0`/inc.sh

arg=${1:-}

if [ "$arg" = "-h" -o "$arg" = "--help" ]; then
    echo "Usage: .bin/relative-urls"
    echo
    echo "Convert absolute URLs into ones relative to server's root"
    echo "So basically remove https://vault.cca.edu from beginning"
    echo "MUST be run from project root (not from inside .bin folder)"
    echo "Runs over all .ftl files inside all subfolders"
    exit 0
fi

# <a> links
sed -i 's|href="https://vault\.cca\.edu||' **/*.ftl
# images
sed -i 's|src="https://vault\.cca\.edu||' **/*.ftl
